# https://learn.microsoft.com/es-mx/aspnet/core/test/http-files?view=aspnetcore-8.0
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@hostname=localhost
@port=3001
@rootUrl=http://{{hostname}}:{{port}}
###
GET {{rootUrl}}/public HTTP/1.1


###
GET {{rootUrl}}/private HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqdWFuIiwibmFtZSI6Ikp1YW4gZmVsaXBlIiwiZXhwIjoxNjg3OTc5Mzc2Nzg0LCJpYXQiOjE2ODc5NzkzMTZ9.nX7QLElU8r-obepEEVdCLu_O7ai43nyt1SZNH9jQUxRcQaY-rPBrklPPts7WLGDoPF62zgxlnHvJHBXhqF2INXR1iXC1-MbVdnaleg6lR_6FYK_Z8q4k2l7PJIAR0Nox3wna1mNJKrOkJr_lFlQ3tPweIXlNiQsnzD0xaLU7FZSRbuGmHRXdWwlxY8G4y9Jh9Duc3HyObYFGhM4t-xCC0Og79ljJReYEGcQhGajPxi3As1-Y8MyKCyaFRr5USpJxnNOAFqhuc8zKarhbe4d9G_VYimSExMNWl0hFr50W6vmgoEjYglzYw551vLWyIp2jche0pRBNfXN51Yu16BHSWQ


###
POST {{rootUrl}}/token HTTP/1.1
Content-Type: application/json
Authorization: Basic juan:7u4n